### ISSUE TITLE
trailing space after continuation 

### ISSUE THREAD

**Issue by olesenm** [HenningScheufler/OpenFOAMGen#1]
Eg, 
https://github.com/HenningScheufler/OpenFOAMGen/blob/afbda29136386717f93b3f27afe060083794f644/OpenFOAMGen/conanfile.py#L25

Should have something like this:
```
incl += "   -I{} \\\n".format(i)
```

Might need to add in some extra placeholder at the end of the loop as well, otherwise the generated file will end with a `\\' as its final line.

**Comment by HenningScheufler** [comment]
fixed in commit cc7ff289cebb7a5cbddaecabe71549c0a985fc4c
